# Configuration file for web scraping pipeline
main:
  queries_file: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/seed_data/test.txt"
  batch_size: 1
  tracker_file: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/storage/processed_queries.txt"

crawler:
  language: "en" # language of sites to return
  pages: 1  # number of pages to return from the search result
  safesearch: 2 # 1 = moderate, 2 = strict, 0=none
  time_range: "year" # date back dated for search results
  timeout: 30 # increase if you face timeout error
  links_file_path: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/storage/raw_links/links.jsonl" # file path to for tracking of global seen links 
  searxng_url: "http://localhost:3628/search" ## searxng docker localhost url
  concurrency: 8 # concurrency should be balanced with timeout, higher concurrency will need more timeout 
  validator_model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507" # validator model to validate if url is sg related
  validator_base_url: "https://hammer-webster-violin-annotated.trycloudflare.com/v1" # vllm url to host the validator model
  validator_workers: 5 

scraper:
  concurrency: 1 # number of links to scrape concurrently
  links_file_path: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/storage/raw_links/links.jsonl" 
  images_dir: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/storage/images_metadata"
  markdown_dir: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/storage/text_data"
  pdf_dir: "/home/leeeefun681/volume/eefun/webscraping2/vlm_webscrape/app/storage/pdf_data"
  validator_model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507" # validator model to validate if url is sg related
  validator_base_url: "https://hammer-webster-violin-annotated.trycloudflare.com/v1" # vllm url to host the validator model