# Configuration file for web scraping pipeline
# --------------------------------------------------
# You can stick to these defaults or increase concurrency/timeouts to speed up scraping.
# All file paths below are repo-relative (assuming you run from project root).
# --------------------------------------------------

main:
  # File containing your list of search queries (one per line)
  queries_file: "./app/seed_data/test.txt"

  # Number of queries to send to the search engine per batch
  batch_size: 1

  # File that tracks which queries have already been processed (to avoid duplicates)
  tracker_file: "./app/storage/processed_queries.txt"


crawler:
  # Search engine query settings
  language: "en"          # language of search results
  pages: 1                # number of pages to fetch per query
  safesearch: 2           # 0=off, 1=moderate, 2=strict
  time_range: "year"      # restrict search results by time
  timeout: 30             # increase if you see frequent timeouts

  # Where to store and read the global link list
  links_file_path: "./app/storage/raw_links/links.jsonl"

  # SearXNG endpoint (update if your container runs on a different port)
  searxng_url: "http://localhost:3628/search"

  # Scraper performance tuning
  concurrency: 8          # higher = faster, but risk of rate limit issues

  # vLLM endpoint used to validate/filter Singapore-related content
  validator_model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507"
  validator_base_url: "https://hammer-webster-violin-annotated.trycloudflare.com/v1"
  validator_workers: 5


scraper:
  # Number of pages to scrape concurrently
  concurrency: 1

  # File that lists links to scrape (same as crawler output)
  links_file_path: "./app/storage/raw_links/links.jsonl"

  # Directories for different scraped outputs
  images_dir: "./app/storage/images_metadata"   # image metadata JSONs
  markdown_dir: "./app/storage/text_data"       # scraped page text in markdown format
  pdf_dir: "./app/storage/pdf_data"             # optional: extracted PDFs (if implemented)

  # Validator model & endpoint (same as crawler)
  validator_model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507"
  validator_base_url: "https://hammer-webster-violin-annotated.trycloudflare.com/v1"
